ARG TAG_VERSION

FROM opensearchproject/logstash-oss-with-opensearch-output-plugin:${TAG_VERSION}

# postgreSQL java driver to enrich data
# RUN curl https://repo1.maven.org/maven2/org/postgresql/postgresql/42.2.5/postgresql-42.2.5.jar -o /usr/share/logstash/config/postgresql-42.2.5.jar
# RUN bin/logstash-plugin install logstash-output-lumberjack logstash-input-lumberjack
