global:
    scrape_interval:     5s
    evaluation_interval: 5s
  
rule_files:
# - "first.rules"
# - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus-node-exporter:9100', 'prometheus-python-app:8000']
