apiVersion: 1
datasources:
  - orgId: 1
    version: 3
    name: Alertmanager
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    jsonData:
      implementation: prometheus
  - orgId: 1
    version: 1
    name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090/
    isDefault: true
