version: "3.7"

services:
  opensearch:
    container_name: opensearch
    build:
      context: opensearch/
      args:
        TAG_VERSION: 1.2.4
    volumes:
      - type: bind
        source: ./opensearch/opensearch.yml
        target: /usr/share/opensearch/config/opensearch.yml
      - type: volume
        source: opensearch
        target: /usr/share/opensearch/data
    ports:
      - 9200:9200
    environment:
      TIMEZONE: America/Sao_Paulo
      TZ: America/Sao_Paulo
      OPENSEARCH_JAVA_OPTS: -Xms512m -Xmx512m

  opensearch-dashboards:
    container_name: opensearch-dashboards
    build:
      context: opensearch-dashboards/
      args:
        TAG_VERSION: 1.2.0
    volumes:
      - type: bind
        source: ./opensearch-dashboards/opensearch_dashboards.yml
        target: /usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
        read_only: true
    ports:
      - 5601:5601
    environment:
      TIMEZONE: America/Sao_Paulo
      TZ: America/Sao_Paulo
      LS_JAVA_OPTS: "-Xmx1g -Xms256m"
    depends_on:
      - opensearch

  logstash:
    container_name: logstash
    build:
      context: logstash/
      args:
        # TAG_VERSION: "7.16.3"
        TAG_VERSION: "latest"
    volumes:
      - type: bind
        source: ./logstash/pipeline/
        target: /usr/share/logstash/pipeline/
        read_only: true
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/config/pipelines.yml
        target: /usr/share/logstash/config/pipelines.yml
        read_only: true
    ports:
      - 5000:5000
    environment:
      TIMEZONE: America/Sao_Paulo
      TZ: America/Sao_Paulo
      LS_JAVA_OPTS: "-Xmx1g -Xms256m"
      LS_OPTS: "--config.reload.automatic"

  filebeat:
    container_name: filebeat
    build:
      context: filebeat/
      args:
        TAG_VERSION: "8.0.1"
    volumes:
      - type: bind
        source: ./filebeat/filebeat.yml
        target: /usr/share/filebeat/filebeat.yml
      - type: bind
        source: ./filebeat/log
        target: /var/log
    environment:
      TIMEZONE: America/Sao_Paulo
      TZ: America/Sao_Paulo
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      HOSTNAME: filebeat

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ./prometheus/rules.yaml:/etc/prometheus/rules.yaml
    ports:
      - 9090:9090
    restart: always

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    volumes:
      - ./alertmanager/pruu.yaml:/etc/alertmanager/config.yml
      - ./alertmanager/templates.tmpl:/etc/alertmanager/configmaps/templates.tmpl
    ports:
      - 9093:9093
    restart: always

  grafana:
    image: grafana/grafana:9.1.5
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=grafana-opensearch-datasource
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/dashboards/:/etc/grafana/provisioning/dashboards/
      - ./grafana/provisioning/datasources/:/etc/grafana/provisioning/datasources/
      - ./grafana/provisioning/dashboards-tree-json/:/etc/dashboards/dashboards-tree-json/

  opensearch_exporter:
    # https://github.com/prometheus-community/elasticsearch_exporter
    build:
      context: opensearch-exporter/
    container_name: opensearch-exporter
    restart: always
    command:
      - '--es.uri=http://opensearch:9200'
      - '--es.ssl-skip-verify'
      - '--es.timeout=5m'
    ports:
      - 9114:9114

  localstack:
    container_name: "localstack-server"
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      DOCKER_HOST: "unix:///var/run/docker.sock"
      SERVICES: "s3"
      DEFAULT_REGION: "us-west-1"
      AWS_DEFAULT_REGION: "us-west-1"
      HOSTNAME_EXTERNAL: "localstack-server"
      HOSTNAME: "localstack-server"
      USE_SSL: "false"
      DEBUG: "1"
    volumes:  
      - "/var/run/docker.sock:/var/run/docker.sock"

  cli:
    container_name: cli
    image: python:3.7
    command: tail -f /dev/null

volumes:
  opensearch:
