---
apiVersion: v1
kind: Namespace
metadata:
  name: app

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  namespace: app

---
apiVersion: v1
kind: Secret
metadata:
  name: app-sa-kubernetes-token
  annotations:
    kubernetes.io/service-account.name: app-sa
type: kubernetes.io/service-account-token

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
  namespace: app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: app-sa
    namespace: app

---
apiVersion: v1
kind: Pod
metadata:
  name: application
  namespace: app
spec:
  serviceAccountName: app-sa
  containers:
    - name: app
      image: amazonlinux:2
      command: ["tail"]
      args: ["-f", "/dev/null"]
