server:
  http_listen_port: 9080
  grpc_listen_port: 0

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 12h

positions:
  filename: /position/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  # https://grafana.com/docs/loki/latest/best-practices/#static-labels-are-good
  static_configs:
  - targets:
      - localhost
    labels:
      host: ${HOST:container-app}
      app: python-app
      job: app-logs
      __path__: /logs/*log
  pipeline_stages:
  - json:
      expressions:
        level: record.level.name
        message: text
        timestamp: record.time.timestamp
        stack_trace: stack_trace
  # - labels:
  #     level:
  - template:
      source: python-loguru
      template: 'level={{ .level }} timestamp={{ .timestamp }} | {{ or .message .stack_trace }}'
  - output:
      source: python-loguru

