services:
  fluentbit:
    container_name: fluentbit
    image: fluent/fluent-bit:latest
    user: root
    volumes:
      - ./fluent-bit.yaml:/fluent-bit/fluent-bit.yaml
    develop:
      watch:
        - action: sync+restart
          path: ./
          target: /fluentbit/
    command:
      - "fluent-bit"
      - "-c"
      - "/fluent-bit/fluent-bit.yaml"

  opensearch:
    container_name: opensearch
    image: opensearchproject/opensearch:2.10.0
    volumes:
      - ./opensearch.yml:/usr/share/opensearch/config/opensearch.yml
    ports:
      - 9200:9200
    environment:
      OPENSEARCH_JAVA_OPTS: -Xms512m -Xmx512m

  opensearch-dashboards:
    container_name: opensearch-dashboards
    image: opensearchproject/opensearch-dashboards:2.10.0
    volumes:
      - ./opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
    ports:
      - 5601:5601
    depends_on:
      - opensearch
