global:
    scrape_interval:     5s
    evaluation_interval: 5s

rule_files:

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['traefik:9100', 'prometheus-exporter:9100']
