---
- name: Mudando o contexto de configuração de organização
  uri:
    url: "{{ grafana.url }}/api/user/using/{{ org_id }}"
    user: "{{ grafana.admin_user }}"
    password: "{{ grafana.admin_password }}"
    method: POST
    force_basic_auth: yes

- name: Criando Datasource do Zabbix
  uri:
    url: "{{ grafana.url }}/api/datasources"
    user: "{{ grafana.admin_user }}"
    password: "{{ grafana.admin_password }}"
    method: POST
    force_basic_auth: yes
    body_format: json
    src: "{{ item }}"
  with_fileglob:
    - "datasources/files/{{ contract }}/*"