version: "3.7"

services:
  grafana:
    container_name: grafana
    image: grafana/grafana:7.3.3
    # user: "1000"
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - 3000:3000

  nginx:
    container_name: nginx
    image: nginx:1.18-alpine
    # user: "1000"
    ports: 
      - 8080:8080
    volumes: 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
