services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  logstash:
    container_name: logstash
    restart: always
    build:
      context: logstash
      args:
        LOGSTASH_IMAGE: docker.elastic.co/logstash/logstash-oss:8.9.2
        JDBC_JAR_DOWNLOAD_URL: https://jdbc.postgresql.org/download/postgresql-42.5.0.jar
    environment:
      DB_USER: user
      DB_PASSWORD: password
      # DB_JDBC_CONNECTION_STRING: jdbc:postgresql://postgres:5432/db
      DB_JDBC_CONNECTION_STRING: jdbc:postgresql://postgres:5432/db?ApplicationName=logstash&loginTimeout=10&socketTimeout=10&options=-c%20statement_timeout=5000%20-c%20lock_timeout=1000
    ports:
      - 8090:8090
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml
