version: '3.8'

services:
  log-generator:
    container_name: log-generator
    user: root
    build:
      context: log-generator
    volumes:
      - logs:/logs
    develop:
      watch:
        - action: sync+restart
          path: ./logs
          target: /logs

  fluentbit:
    container_name: fluentbit
    image: fluent/fluent-bit:latest
    user: root
    volumes:
      - logs:/logs
      - ./fluentbit/fluent-bit.yaml:/fluent-bit/fluent-bit.yaml
    develop:
      watch:
        - action: sync+restart
          path: ./fluentbit/fluent-bit.yaml
          target: /fluent-bit/fluent-bit.yaml
    command:
      - "fluent-bit"
      - "-c"
      - "/fluent-bit/fluent-bit.yaml"

  http-server:
    container_name: http-server
    user: root
    build:
      context: http-server

volumes:
  logs:
