apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  # labels:
  #   app: my-app
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 1 
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: nginx-1
        image: nginx
        ports:
        - containerPort: 80
      # - name: nginx-2
      #   image: nginx
      #   ports:
      #   - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingrees
spec:
  rules:
  - host: "nginx-1.localhost"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: service-nginx-1
            port:
              number: 8081
  # - host: "nginx-2.localhost"
  #   http:
  #     paths:
  #     - pathType: Prefix
  #       path: "/"
  #       backend:
  #         service:
  #           name: service-nginx-2
  #           port:
  #             number: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: service-nginx-1
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80

# ---
# apiVersion: networking.k8s.io/v1beta
# kind: Service
# metadata:
#   name: service-nginx-2
# spec:
#   selector:
#     app: my-app
#   ports:
#     - protocol: TCP
#       port: 8081
#       targetPort: 80
