apiVersion: "v1"
kind: "Pod"
metadata: 
  name: "my-nginx"
spec:
  containers:
    - image: nginx
      name: my-nginx
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
