apiVersion: v1
kind: Pod
metadata:
  name: liveness-test-http
spec:
  containers:
  - name: liveness
    image: k8s.gcr.io/liveness
    args:
    - /server
    ports:
      # kubectl port-forward liveness-test-http 8080:healthy-checker
      - containerPort: 8080
        name: healthy-checker
        protocol: TCP
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
        httpHeaders:
        - name: Custom-Header
          value: Awesome
      initialDelaySeconds: 3
      periodSeconds: 3
