apiVersion: v1
kind: Pod
metadata:
  name: liveness-test-http
spec:
  containers:
  - name: liveness
    image: k8s.gcr.io/liveness
    args:
    - /server
    resources:
      cpu: 500m
      memory: 128Mi 