version: "3.7"

services:
  opensearch:
    container_name: opensearch
    build:
      context: opensearch/
      args:
        TAG_VERSION: "latest"
    volumes:
      - type: bind
        source: ./opensearch/opensearch.yml
        target: /usr/share/opensearch/config/opensearch.yml
      - type: volume
        source: opensearch
        target: /usr/share/opensearch/data
    ports:
      - 9200:9200
    environment:
      TIMEZONE: America/Sao_Paulo
      TZ: America/Sao_Paulo
      OPENSEARCH_JAVA_OPTS: -Xms512m -Xmx512m

  opensearch-dashboards:
    container_name: opensearch-dashboards
    build:
      context: opensearch-dashboards/
      args:
        TAG_VERSION: "latest"
    volumes:
      - type: bind
        source: ./opensearch-dashboards/opensearch_dashboards.yml
        target: /usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
        read_only: true
    ports:
      - 5601:5601
    environment:
      TIMEZONE: America/Sao_Paulo
      TZ: America/Sao_Paulo
      LS_JAVA_OPTS: "-Xmx1g -Xms256m"
    depends_on:
      - opensearch

  logstash:
    container_name: logstash
    build:
      context: logstash/
      args:
        TAG_VERSION: "latest"
    volumes:
      - type: bind
        source: ./logstash/pipeline/
        target: /usr/share/logstash/pipeline/
        read_only: true
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/config/pipelines.yml
        target: /usr/share/logstash/config/pipelines.yml
        read_only: true
    ports:
      - 5000:5000
    environment:
      TIMEZONE: America/Sao_Paulo
      TZ: America/Sao_Paulo
      LS_JAVA_OPTS: "-Xmx1g -Xms256m"
      LS_OPTS: "--config.reload.automatic"

  filebeat:
    container_name: filebeat
    build:
      context: filebeat/
      args:
        TAG_VERSION: "8.0.1"
    volumes:
      - type: bind
        source: ./filebeat/filebeat.yml
        target: /usr/share/filebeat/filebeat.yml
      - type: bind
        source: ./filebeat/log
        target: /var/log
    environment:
      TIMEZONE: America/Sao_Paulo
      TZ: America/Sao_Paulo
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      HOSTNAME: filebeat


volumes:
  opensearch:
