server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /volume/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          __path__: /var/log/traefik/access.log
          job: /var/log/traefik/access.log

  # - job_name: system
  #   static_configs:
  #     - targets:
  #         - localhost
  #       labels:
  #         __path__: /var/log/containers/*log
  #   pipeline_stages:
  #     - json:
  #         expressions:
  #           message: text
  #           timestamp: record.time.timestamp
  #           client-id: record.extra.client-id
  #     - template:
  #         source: python-loguru
  #         template: 'timestamp={{ .timestamp }} client-id={{ .component }} {{ .message }}'
  #     - output:
  #         source: python-loguru
  #     - labels:
  #         client-id:

  # - job_name: nginx
  #   static_configs:
  #     - targets:
  #         - localhost
  #       labels:
  #         job: nginx_access_log
  #         agent: promtail
  #         __path__: /var/log/nginx/*access.log
  #   pipeline_stages:
  #     - replace:
  #         expression: '(?:[0-9]{1,3}\.){3}([0-9]{1,3})'
  #         replace: '***'

