---
kind: Service
apiVersion: v1
metadata:
  name: os-cluster-manager
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: os-cluster-manager
  ports:
    - name: http
      protocol: TCP
      port: 9200
    - name: transport
      protocol: TCP
      port: 9300
    - name: metrics
      protocol: TCP
      port: 9600

---
kind: Service
apiVersion: v1
metadata:
  name: os-ingest
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: os-ingest
  ports:
    - name: http
      protocol: TCP
      port: 9200
    - name: transport
      protocol: TCP
      port: 9300
    - name: metrics
      protocol: TCP
      port: 9600

---
kind: Service
apiVersion: v1
metadata:
  name: os-coordinating
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: os-coordinating
  ports:
    - name: http
      protocol: TCP
      port: 9200
    - name: transport
      protocol: TCP
      port: 9300
    - name: metrics
      protocol: TCP
      port: 9600
