version: "3.7"


volumes:
  minio-br-storage:
  minio-us-storage:
  prometheus-server-storage:
  loki-storage:
  promtail-storage:
  traefik-analitcs-logs-storage:


services:
  traefik:
    image: traefik:v2.5
    container_name: traefik
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/:/etc/traefik/:ro
      - traefik-analitcs-logs-storage:/var/log/traefik
    env_file: 
      - env-traefik.env
    expose: 
      - 9100
      - 8081
      - 8080
      - 8090
    ports:
      - 8081:8081
      - 8090:8090

  auth-server:
    container_name: auth-server
    build: 
      context: auth-server
    expose: 
      - 8090

  promtail:
    image: grafana/promtail:2.1.0
    container_name: promtail
    command: 
      - '-config.file=/etc/promtail/config.yml'
      - '-config.expand-env=true'
    volumes: 
      - ./promtail/config.yml:/etc/promtail/config.yml:ro
      - traefik-analitcs-logs-storage:/var/log/traefik:ro
      - promtail-storage:/volume:rw
    ports:
      - 9080:9080

  prometheus-exporter:
    image: prom/node-exporter:master
    container_name: prometheus-exporter
    restart: always
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /data:/rootfs:ro
    expose: 
      - 9100

  loki:
    image: grafana/loki:2.0.0
    container_name: loki
    command: 
      - -config.file=/etc/loki/config.yml
      - -print-config-stderr=true
    volumes:
      - ./loki/config.yml:/etc/loki/config.yml:ro
      - loki-storage:/loki:rw
    expose: 
      - 3100

  prometheus-server:
    image: prom/prometheus:latest
    container_name: prometheus-server
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
    volumes:
      - ./prometheus-server/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-server-storage:/prometheus:rw
    expose: 
      - 9090

  grafana:
    image: grafana/grafana:8.1.2
    container_name: grafana
    restart: always
    env_file: 
      - env-grafana.env
    volumes: 
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./grafana/dashboards-tree-json:/etc/dashboards/dashboards-tree-json:ro
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      # - ./grafana/assets/icon.svg:/usr/share/grafana/public/img/grafana_icon.svg:ro
    expose: 
      - 3000

  # minio-br-1:
  #   image: minio/minio
  #   container_name: minio-br-1
  #   restart: always
  #   command: server /data --console-address ":9001"
  #   volumes:
  #     - minio-br-storage:/data
  #   env_file: 
  #     - env-minio-br.env
  #   expose:
  #     - 9000
  #     - 9001

  # minio-br-2:
  #   extends: minio-br-1
  #   container_name: minio-br-2
