global:
  slack_api_url: https://hooks.slack.com/services/

templates: ["/etc/alertmanager/configmaps/*.tmpl"]

route:
  # receiver: "slack-notifications"
  receiver: "slack"
  group_wait: 5s
  group_interval: 5s
  repeat_interval: 5s

receivers:
  - name: "slack-notifications"
    slack_configs:
      - channel: "#tests"
        text: "test"
        send_resolved: true
  - name: slack
    slack_configs:
      - channel: "#tests"
        color: '{{ template "slack.color" . }}'
        title: '{{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}'
        send_resolved: true
        actions:
          - type: button
            text: "Runbook :green_book:"
            url: "{{ (index .Alerts 0).Annotations.runbook_url }}"
          - type: button
            text: "Query :mag:"
            url: "{{ (index .Alerts 0).GeneratorURL }}"
          - type: button
            text: "Dashboard :chart_with_upwards_trend:"
            url: "{{ (index .Alerts 0).Annotations.dashboard_url }}"
          - type: button
            text: "Silence :no_bell:"
            url: '{{ template "__alert_silence_link" . }}'
