on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js action
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: tests...
        run: cat /etc/*release
